(self.AMP=self.AMP||[]).push({n:"amp-font",v:"1490899213109",f:(function(AMP){function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var e in b)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,e);d&&Object.defineProperty(a,e,d)}else a[e]=b[e]};Date.now();self.log=self.log||{user:null,dev:null};var m=self.log;function p(){if(m.user)return m.user;throw Error("failed to call initLogConstructor");};function q(a){a=a.__AMP_TOP||a;var b=a.services&&a.services.timer&&a.services.timer.obj;return b}function r(a){var b,c=a=a.__AMP_TOP||a,e=b?b:void 0,d=a.services;d||(d=a.services={});a=d;(d=a.vsync)||(d=a.vsync={obj:null,promise:null,resolve:null,build:null});d.obj||(d.obj=d.build?d.build():e(c),d.resolve&&d.resolve(d.obj));return d.obj};var t,u="Webkit webkit Moz moz ms O o".split(" ");function v(a,b){for(var c in b){var e=a,d=b[c],f;f=e.style;var h=c;t||(t=Object.create(null));var k=t[h];if(!k){k=h;if(void 0===f[h]){var g;g=h;g=g.charAt(0).toUpperCase()+g.slice(1);a:{for(var n=0;n<u.length;n++){var w=u[n]+g;if(void 0!==f[w]){g=w;break a}}g=""}void 0!==f[g]&&(k=g)}t[h]=k}(f=k)&&(e.style[f]=d)}};var x=["sans-serif","serif"];function y(a){this.s=a;this.a=a.document;this.c=null;this.l=this.m=!1;this.b=null}y.prototype.load=function(a,b){var c=this;this.b=a;return q(this.s).timeoutPromise(b,z(this)).then(function(){c.m=!0;c.f()},function(a){c.l=!0;c.f();throw a;})};
function z(a){return new Promise(function(b,c){var e=a.b.style+" "+a.b.variant+" "+a.b.weight+" "+a.b.size+" '"+a.b.family+"'";"fonts"in a.a?a.a.fonts.check(e)?b():a.a.fonts.load(e).then(function(){return a.a.fonts.load(e)}).then(function(){a.a.fonts.check(e)?b():c(Error("Font could not be loaded, probably due to incorrect @font-face."))}).catch(c):A(a).then(b,c)})}
function A(a){return new Promise(function(b,c){var e=r(a.s),d=B(a),f=e.createTask({measure:function(){a.m?b():a.l?c(Error("Font loading timed out.")):d.some(function(a){return a.compare()})?b():f()}});f()})}
function B(a){var b=a.c=a.a.createElement("div");v(b,{fontSize:"40px",fontVariant:a.b.variant,fontWeight:a.b.weight,fontStyle:a.b.style,left:"-999px",lineHeight:"normal",margin:0,padding:0,position:"absolute",top:"-999px",visibility:"hidden"});var c=x.map(function(c){return new C(b,a.b.family,c)});a.a.body.appendChild(b);return c}y.prototype.f=function(){if(this.c){var a=this.c;a.parentElement&&a.parentElement.removeChild(a)}this.c=null};
function C(a,b,c){var e=a.ownerDocument,d=b+","+c;this.g=D(e,c);this.h=D(e,d);a.appendChild(this.g);a.appendChild(this.h)}function D(a,b){a=a.createElement("div");a.textContent="MAxmTYklsjo190QW";v(a,{float:"left",fontFamily:b,margin:0,padding:0,whiteSpace:"nowrap"});return a}C.prototype.compare=function(){var a=2<Math.abs(this.g.offsetWidth-this.h.offsetWidth),b=2<Math.abs(this.g.offsetHeight-this.h.offsetHeight);return a||b};function E(a){AMP.BaseElement.apply(this,arguments)}l(E,AMP.BaseElement);E.prototype.prerenderAllowed=function(){return!0};
E.prototype.buildCallback=function(){this.j=p().assert(this.element.getAttribute("font-family"),"The font-family attribute is required for <amp-font> %s",this.element);this.w=this.element.getAttribute("font-weight")||"400";this.u=this.element.getAttribute("font-style")||"normal";this.v=this.element.getAttribute("font-variant")||"normal";this.a=this.win.document;this.i=this.a.documentElement;this.o=new y(this.win);F(this)};
function F(a){a.o.load({style:a.u,variant:a.v,weight:a.w,size:"medium",family:a.j},G(a)).then(function(){var b=a.element.getAttribute("on-load-add-class"),c=a.element.getAttribute("on-load-remove-class");H(a,b,c)}).catch(function(){var b=a.element.getAttribute("on-error-add-class"),c=a.element.getAttribute("on-error-remove-class");H(a,b,c);p().warn("amp-font","Font download timed out for "+a.j)})}
function H(a,b,c){b&&a.i.classList.add(b);c&&(a.i.classList.remove(c),a.a.body.classList.remove(c));a.f()}E.prototype.f=function(){this.o=null};function G(a){var b=parseInt(a.element.getAttribute("timeout"),10),c=b,b="number"!==typeof c||!isFinite(c)||0>b?3E3:b;return b=Math.max(b-q(a.win).timeSinceStart(),100)}AMP.registerElement("amp-font",E);
})});
//# sourceMappingURL=amp-font-0.1.js.map

